const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "food-1.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },

  {
    id: "2",
    name: "Hamburger",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["USA"],
    stars: 4.5,
    imageUrl: "food-2.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "3",
    name: "Meat Ball",
    cookTime: "20",
    price: 15,
    favorite: true,
    origins: ["Persia", "Middle east", "China"],
    stars: 6,
    imageUrl: "food-3.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "4",
    name: "Kebab",
    cookTime: "8",
    price: 7,
    favorite: true,
    origins: ["Italy"],
    stars: 7,
    imageUrl: "food-4.png",
    tags: ["FastFood", "Turkey"],
  },
  {
    id: "5",
    name: "Ragu",
    cookTime: "20",
    price: 15,
    favorite: true,
    origins: ["Italy"],
    stars: 5,
    imageUrl: "food-5.png",
    tags: ["FastFood", "Lunch"],
  },
  {
    id: "6",
    name: "Lazania",
    cookTime: "8",
    price: 7,
    favorite: true,
    origins: ["Italy"],
    stars: 7,
    imageUrl: "food-6.png",
    tags: ["FastFood", "Italian", "Lunch"],
  },
];

export default sample_foods;
